spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/sisdis?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
       resourceserver:
          jwt:
            issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_ID}


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:eu-north-1}
    s3:
      bucket: ${S3_BUCKET:publications-bucket}
    cognito:
      user-pool-id: us-east-1_xrcihwhrv

server:
  compression:
    enabled: 'true'
  port: '8080'
